Style/Encoding:
    Enabled: false

Style/SymbolArray:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/GuardClause:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Style/FormatStringToken:
    Enabled: false

Layout/IndentationWidth:
    Description: 'Use 4 spaces for indentation.'
    Enabled: true
    Width: 4

Layout/EndOfLine:
    Description: 'Use Unix-style line endings.'
    Enabled: true
    EnforcedStyle: lf

Bundler/OrderedGems:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Description: 'Avoid methods longer than 50 lines of code.'
    Enabled: true
    Max: 50

Metrics/BlockLength:
    Description: 'Avoid blocks longer than 50 lines of code.'
    Enabled: true
    Max: 50

Metrics/LineLength:
    Description: 'Limit lines to 120 characters.'
    Enabled: true
    Max: 120
