language: ruby
rvm:
  - 2.4.2
bundler_args: --without production
group: stable
dist: precise
os: linux
services:
    - mongodb
env:
  - MOEVERDOSE_DEV_HOST=localhost MOEVERDOSE_DEV_PORT=3000

after_success:
  - wget https://raw.githubusercontent.com/eternialz/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success

after_failure:
  - wget https://raw.githubusercontent.com/eternialz/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure
