language: ruby
rvm:
  - 2.5.3
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
bundler_args: --without production
group: stable
dist: xenial
os: linux
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  - MOEVERDOSE_DEV_HOST=localhost MOEVERDOSE_DEV_PORT=3000 TRAVISCI=true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsodium-dev
  - gem update --system
  - gem install bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./bin/yarn

script:
  - RAILS_ENV=test bundle exec spring rails db:migrate
  - RAILS_ENV=test bundle exec spring rake

after_success:
  - wget https://raw.githubusercontent.com/eternialz/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success

after_failure:
  - wget https://raw.githubusercontent.com/eternialz/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure
