# RAILS
export SECRET_KEY_BASE=
export SECRET_KEY_DEV=
export SECRET_KEY_TEST=

# DEVISE
export SECRET_KEY_DEVISE=

# DISCORD
## webhook
export DISCORD_WEBHOOK_POSTS_URL=

## bot
export DISCORD_BOT_USER_TOKEN=
export DISCORD_CLIENT_ID=

# MOEVERDOSE
## dev
export MOEVERDOSE_DEV_HOST=localhost
export MOEVERDOSE_DEV_PORT=3000

export MOEVERDOSE_PROD_HOST=
export MOEVERDOSE_PROD_PORT=

#TWITTER
export TWITTER_CONSUMER_KEY=
export TWITTER_CONSUMER_SECRET=
export TWITTER_ACCESS_TOKEN=
export TWITTER_ACCESS_SECRET=
